<?php

    // autoload.php @generated by ShiroAky
    date_default_timezone_set('America/Santo_Domingo');

    spl_autoload_register(function ($__CLASS__NAME) {

        $__VENDOR__NAMESPACE = 'App';
        $__BASE_DIR = '../app/';

        $__SIN_VENDOR_NAMESPACE = str_replace("$__VENDOR__NAMESPACE\\", '', $__CLASS__NAME);
        $__RUTE_INTO_BASE = str_replace('\\', DIRECTORY_SEPARATOR, $__SIN_VENDOR_NAMESPACE);

        $__FILE_NAME = sprintf('%s%s.php', $__BASE_DIR, $__RUTE_INTO_BASE);

        if (file_exists($__FILE_NAME)) {
            require_once $__FILE_NAME;
        } else {
            $__DATE = date('Y_d_m');
            file_put_contents("../logs/Error_$__DATE" . '_' . time() . '.log', "Error to load class where $__FILE_NAME");
        }

    });