<?php

    // autoload.php @generated by ShiroAky

    spl_autoload_register(function ($__CLASS__NAME) {

        $__VENDOR__NAMESPACE = '{Your main namespace name}';
        $__BASE_DIR = '../{Your main project directory}';

        $__SIN_VENDOR_NAMESPACE = str_replace("$__VENDOR__NAMESPACE\\", '', $__CLASS__NAME);
        $__RUTE_INTO_BASE = str_replace('\\', DIRECTORY_SEPARATOR, $__SIN_VENDOR_NAMESPACE);

        $__FILE_NAME = sprintf('%s%s.php', $__BASE_DIR, $__RUTE_INTO_BASE);

        if (file_exists($__FILE_NAME)) { require_once $__FILE_NAME; } 
        else { return 'Failed to load class'; exit; }
        
    });
